// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Com.Prerit.Controllers {
    [CompilerGenerated]
    public partial class AccountsController {
        protected AccountsController(Dummy d) { }

        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = (IT4MVCActionResult)result;
            return RedirectToRoute(callInfo.RouteValues);
        }

        [NonAction]
        public System.Web.Mvc.ActionResult LogIn() {
            return new T4MVC_ActionResult(Area, Name, Actions.LogIn);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult Logout() {
            return new T4MVC_ActionResult(Area, Name, Actions.Logout);
        }

        public readonly string Area = "";
        public readonly string Name = "Accounts";

        static readonly ActionNames s_actions = new ActionNames();
        public ActionNames Actions { get { return s_actions; } }
        public class ActionNames {
            public readonly string LogIn = "LogIn";
            public readonly string LoginStatus = "LoginStatus";
            public readonly string Logout = "Logout";
        }


        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
            public readonly string LoggedInStatus = "~/Views/Accounts/LoggedInStatus.ascx";
            public readonly string LoggingInStatus = "~/Views/Accounts/LoggingInStatus.ascx";
            public readonly string LogIn = "~/Views/Accounts/LogIn.aspx";
            public readonly string NotLoggedInStatus = "~/Views/Accounts/NotLoggedInStatus.ascx";
        }
    }

    [CompilerGenerated]
    public class T4MVC_AccountsController: Com.Prerit.Controllers.AccountsController {
        public T4MVC_AccountsController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult LogIn(string returnUrl) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.LogIn);
            callInfo.RouteValues.Add("returnUrl", returnUrl);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult LoginStatus() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.LoginStatus);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Logout(string returnUrl) {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Logout);
            callInfo.RouteValues.Add("returnUrl", returnUrl);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
