// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Com.Prerit.Controllers {
    [CompilerGenerated]
    public partial class DefaultMasterController {
        public DefaultMasterController() { }

        protected DefaultMasterController(Dummy d) { }

        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = (IT4MVCActionResult)result;
            return RedirectToRoute(callInfo.RouteValues);
        }


        public readonly string Area = "";
        public readonly string Name = "DefaultMaster";

        static readonly ActionNames s_actions = new ActionNames();
        public ActionNames Actions { get { return s_actions; } }
        public class ActionNames {
            public readonly string ContentEncoding = "ContentEncoding";
            public readonly string ContentType = "ContentType";
            public readonly string Culture = "Culture";
            public readonly string CurrentUrlEncoded = "CurrentUrlEncoded";
            public readonly string Year = "Year";
        }


        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
        }
    }

    [CompilerGenerated]
    public class T4MVC_DefaultMasterController: Com.Prerit.Controllers.DefaultMasterController {
        public T4MVC_DefaultMasterController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult ContentEncoding() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.ContentEncoding);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ContentType() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.ContentType);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Culture() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Culture);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult CurrentUrlEncoded() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.CurrentUrlEncoded);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Year() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.Year);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
