// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Com.Prerit.Controllers {
    [CompilerGenerated]
    public partial class ResumeFormatsController {
        public ResumeFormatsController() { }

        protected ResumeFormatsController(Dummy d) { }

        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = (IT4MVCActionResult)result;
            return RedirectToRoute(callInfo.RouteValues);
        }


        public readonly string Area = "";
        public readonly string Name = "ResumeFormats";

        static readonly ActionNames s_actions = new ActionNames();
        public ActionNames Actions { get { return s_actions; } }
        public class ActionNames {
            public readonly string AdobePdf = "AdobePdf";
            public readonly string MicrosoftWord = "MicrosoftWord";
        }


        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
        }
    }

    [CompilerGenerated]
    public class T4MVC_ResumeFormatsController: Com.Prerit.Controllers.ResumeFormatsController {
        public T4MVC_ResumeFormatsController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult AdobePdf() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.AdobePdf);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult MicrosoftWord() {
            var callInfo = new T4MVC_ActionResult(Area, Name, Actions.MicrosoftWord);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
